---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mingyong.
--- DateTime: 2020/5/17 11:26 上午
---

a = "one string"
b = string.gsub(a,"one","another") -- like golang strings.ReplaceAll function
print(a)  -- "one string"
print(b) -- "another string"

a="hello"
print(#a)    -- 5
print(#"good byte") -- 9

print("Hello".."World") --HelloWorld
print("result is "..3) --result is 3

-- constant string
a = "a line"
b = 'another line'

print("one line\nnext line\n\"in quotes\",'in quotes'")




